using Nerve.Repository.Dtos;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Nerve.Repository
{
    public interface IGenericMasterRepository
    {
        //Model
        Task<List<ProductModelDto>> GetAllProductModelAsync();
        Task<List<ProductModelDto>> GetProductModelAsync(string productName);
        Task<List<ProductModelDto>> GetProductModelByNameAndBrandAsync(string productName, string brandName);

        //Fault Codes
        Task<List<FaultDetailDto>> GetFaultCodesByBrandAsync(string brandName);

        //Physical Conditions
        Task<List<PhysicalConditionDto>> GetPhysicalConditionsAsync();

        //Reference
        Task<string> GetAutoGeneratedDocumentNumberAsync(int year, string prefix);
    }
}
