using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nerve.Web
{
    /// <summary>
    /// Defined all language keys constant as per json file.
    /// Every time creating any constant key here than make sure corresponding key should be in every json file for each language.
    /// </summary>
    public class LanguageKeys
    {
        public const string Accessories = "accessories";
        public const string AdditionalSerialNumber = "additional-serial-number";
        public const string AirwayBillNumber = "airway-bill-number";
        public const string AutoCrn = "auto-crn";
        public const string Battery = "battery";
        public const string Brand = "brand";
        public const string Charger = "charger";
        public const string Clear = "clear";
        public const string CollectedDate = "collected-date";
        public const string CollectionPoint = "collection-point";
        public const string CollectionPointCode = "collection-point-code";
        public const string CollectionPointName = "collection-point-name";
        public const string CreditLimtRecouncillationReport = "credit-limt-recouncillation-report";
        public const string CrnSlashRmaNumber = "crn-slash-rma-number";
        public const string CustomerName = "customer-name";
        public const string CustomerAddress = "customer-address";
        public const string CustomerFirstName = "customer-first-name";
        public const string CustomerLastName = "customer-last-name";
        public const string DebitNoteEntry = "debit-note-entry";
        public const string Delete = "delete";
        public const string DeviceLogin = "device-login";
        public const string DispatchDate = "dispatch-date";
        public const string DispatchNote = "dispatch-note";
        public const string DoA = "doa";
        public const string EcoCode = "eco-code";
        public const string Email = "email";
        public const string English = "english";
        public const string EngineeringActivity = "engineering-activity";
        public const string Estimation = "estimation";
        public const string EstimationApproval = "estimation-approval";
        public const string Exit = "exit";
        public const string ExpireDate = "expiry-date";
        public const string Farsi = "farsi";
        public const string FaultAndAccessoryDetails = "fault-and-accessory-details";
        public const string FaultCode = "fault-code";
        public const string FaultDetails = "fault-details";
        public const string Find = "find";
        public const string FindNow = "find-now";
        public const string Forwarder = "forwarder";
        public const string FrontDesk = "front-desk";
        public const string Grn = "grn";
        public const string Hami = "hami";
        public const string Home = "home";
        public const string ImeiNumber = "imei-number";
        public const string ImeiHistory = "imei-history";
        public const string Inventory = "inventory";
        public const string Issued = "issued";
        public const string JobAllocation = "job-allocation";
        public const string JobClosing = "job-closing";
        public const string JobNumber = "job-number";
        public const string LoginDetails = "login-details";
        public const string Logout = "logout";
        public const string LogDate = "log-date";
        public const string MobileNumber = "mobile-number";
        public const string Model = "model";
        public const string NationalId = "national-id";
        public const string NonHami = "non-hami";
        public const string NonWarrantyCustomerApproval = "non-warranty-customer-approval";
        public const string NonWarrantyInvoice = "non-warranty-invoice";
        public const string Operations = "operations";
        public const string Other = "other";
        public const string Password = "password";
        public const string PaymentRegister = "payment-register";
        public const string Payments = "payments";
        public const string PendingCustomerApproval = "pending-customer-approval";
        public const string PendingGrn = "pending-grn";
        public const string PendingPayment = "pending-payment";
        public const string PendingPurchaseEstimation = "pending-purchase-estimation";
        public const string PendingPurchaseEstimationApproval = "pending-purchase-estimation-approval";
        public const string PendingPurchaseOrder = "pending-purchase-order";
        public const string PendingPurchaseRequest = "pending-purchase-request";
        public const string PendingRTVApproval = "pending-rtv-approval";
        public const string PendingRTVRequest = "pending-rtv-request";
        public const string PendingSalesOrder = "pending-sales-order";
        public const string PendingSalesRetrun = "pending-sales-retrun";
        public const string PendingStatusReport = "pending-status-report";
        public const string PhysicalCondition = "physical-condition";
        public const string PopDate = "pop-date";
        public const string PopPath = "pop-path";
        public const string PopUpload = "pop-upload";
        public const string Print = "print";
        public const string Product = "product";
        public const string PurchaseEstimation = "purchase-estimation";
        public const string PurchaseEstimationConfirmation = "purchase-estimation-confirmation";
        public const string PurchaseOrder = "purchase-order";
        public const string PurchaseRequest = "purchase-request";
        public const string PurchaseReturn = "purchase-return";
        public const string Queries = "queries";
        public const string Returned = "returned";
        public const string ReEstimation = "re-estimation";
        public const string Reports = "reports";
        public const string Remarks = "remarks";
        public const string RtvApproval = "rtv-approval";
        public const string RtvRequest = "rtv-request";
        public const string SalesOrder = "sales-order";
        public const string SalesReturn = "sales-return";
        public const string Save = "save";
        public const string SmsLanguage = "sms-language";
        public const string SparePartIssue = "spare-part-issue";
        public const string SparePartRequest = "spare-part-request  ";
        public const string SparePartsRecouncillationReport = "spare-parts-recouncillation-report";
        public const string SpCreditLimit = "sp-credit-limit";
        public const string StandByUnits = "stand-by-units";
        public const string StatusHistory = "status-history";
        public const string StatusRegister = "status-register";
        public const string SearchCriteria = "search-criteria";
        public const string ServiceCentre = "service-centre";
        public const string TelephoneNumber = "telephone-number";
        public const string TransferTo = "transfer-to";
        public const string TrackingNumber = "tracking-number";
        public const string Transaction = "transaction";
        public const string Transactions = "transactions";
        public const string Type = "type";
        public const string Undo = "undo";
        public const string UnitDroppedDate = "unit-dropped-date";
        public const string VendorRmaUpdation = "vendor-rma-updation";
        public const string VendorRmaNumber = "vendor-rma-number";
        public const string WaitingforDispathInvoice = "waiting-for-dispath-invoice";
        public const string WarrantyChange = "warranty-change";
        public const string WarrantyInvoice = "warranty-invoice";
        public const string WarrantyType = "warranty-type";
        public const string WelcomeToNerveLogistics = "welcome-to-nerve-logistics";
        public const string ImeiSlashSerialNumber = "imei-slash-serial-no";
    }
}
