using Nerve.Repository;
using Nerve.Repository.Dtos;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Nerve.Service
{
    public class GenericMasterService : IGenericMasterService
    {
        private readonly IGenericMasterRepository _genericMasterRepository;
        public GenericMasterService(IGenericMasterRepository genericMasterRepository)
        {
            _genericMasterRepository = genericMasterRepository;
        }

        #region Fault Codes
        public async Task<List<FaultDetailDto>> GetFaultCodesByBrandAsync(string brandName)
        {
            return await _genericMasterRepository.GetFaultCodesByBrandAsync(brandName);
        }
        #endregion

        #region Physical Condition
        public async Task<List<PhysicalConditionDto>> GetPhysicalConditionsAsync()
        {
            return await _genericMasterRepository.GetPhysicalConditionsAsync();
        }

        #endregion

        public async Task<string> GetAutoGeneratedTrackingNumberAsync(int year, string prefix)
        {
            return await _genericMasterRepository.GetAutoGeneratedDocumentNumberAsync(year, prefix);
        }
    }
}
