ALTER TABLE [HAMI_SCP].dbo.WEB_MENUMASTER ADD LanguageKey VARCHAR(250) NOT NULL DEFAULT ('no-key-avaialble')
ALTER TABLE [HAMI_SCP].dbo.WEB_MENUMASTER ADD ModuleID INT NOT NULL DEFAULT (6)

UPDATE [HAMI_SCP].dbo.WEB_MENUMASTER SET LanguageKey = LOWER(REPLACE(MenuName,' ','-'))

--REMOVE DUPLICATE FOR WEB_USERRIGHTS
;WITH DUPLICATE
AS
(
	SELECT ROW_NUMBER() OVER(PARTITION BY GROUPID, MODULEID, MENUID ORDER BY GROUPID, MODULEID, MENUID) AS ROW_NO,
	* FROM [dbo].[WEB_USERRIGHTS]
)

DELETE FROM DUPLICATE WHERE ROW_NO = 2

--MENU LINKING WITH ACTUAL PAGE
UPDATE [HAMI_SCP].[dbo].[WEB_MENUMASTER] SET MenuLink ='/Device/Index' WHERE MenuName = 'Device Login' AND ModuleID = 6