using Nerve.Repository;
using Nerve.Repository.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nerve.Service
{
    class DeviceService : IDeviceService
    {
        private readonly IDeviceRepository _deviceRepository;
        private readonly IGenericMasterRepository _genericMasterRepository;
        private readonly IJobRepository _jobRepository;
        private readonly IServiceCentreLocationRepository _serviceCentreLocationRepository;
        public DeviceService(IDeviceRepository deviceRepository,
            IGenericMasterRepository genericMasterRepository,
            IJobRepository jobRepository,
            IServiceCentreLocationRepository serviceCentreLocationRepository)
        {
            _deviceRepository = deviceRepository;
            _genericMasterRepository = genericMasterRepository;
            _jobRepository = jobRepository;
            _serviceCentreLocationRepository = serviceCentreLocationRepository;
        }

        /// <summary>
        /// Authenticate device for any existing job running or not.
        /// </summary>
        /// <param name="imeiNumber"></param>
        /// <returns></returns>
        public async Task<bool> DeviceAuthenticateAsync(string imeiNumber)
        {
            return await _deviceRepository.DeviceAuthenticationAsync(imeiNumber);
        }

        public async Task<bool> SaveAsync(DeviceDto deviceDto)
        {
            //get document number 
            var documentNumber = await _genericMasterRepository.GetAutoGeneratedDocumentNumberAsync(DateTime.Now.Year, deviceDto.Prefix);
            if(string.IsNullOrEmpty(documentNumber))
            {
                throw new InvalidOperationException();
            }

            deviceDto.AutoGenerateDocumentNumber = documentNumber;

            //get job number 
            var jobNumber = await _jobRepository.GetJobReferenceNumberAsync(deviceDto.LocationCode);
            if (string.IsNullOrEmpty(jobNumber))
            {
                throw new InvalidOperationException();
            }
            
            deviceDto.AutoJobNumber = jobNumber;

            // DOA is true
            // write here code for Pop Upload.

            var serviceCentreLocations = await _serviceCentreLocationRepository.GetByIdAndBrandAndProductAsync(deviceDto.CollectionPoint, deviceDto.Product, deviceDto.Brand);
            if (serviceCentreLocations!=null && serviceCentreLocations.Any())
            {
                var serviceCentreLocation = serviceCentreLocations.Select(x => new ServiceCentreLocationDto
                {
                    LocationCode = x.LocationCode,
                    City = x.City,
                    DetailId = x.DetailId,
                    LocationName = x.LocationName
                }).Distinct().FirstOrDefault();

                deviceDto.LocationCode = serviceCentreLocation.LocationCode;
                deviceDto.City = serviceCentreLocation.City;
                deviceDto.DetailId = serviceCentreLocation.DetailId;
            }

            deviceDto.AutoGenerateDocumentNumber = documentNumber;
            return await _deviceRepository.SaveAsync(deviceDto);
        }
    }
}
